version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
      POSTGRES_DB: ${POSTGRES_DB:-bankruptcy_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # pgAdmin (optional for development)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@bankruptcy.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-secure_admin_password}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    profiles:
      - dev  # Only start with --profile dev

  # MLflow Tracking Server
  mlflow:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_password_change_me}@postgres:5432/mlflow
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=./artifacts
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - mlflow_artifacts:/app/artifacts
    restart: unless-stopped
    command: >
      mlflow server 
      --backend-store-uri postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_password_change_me}@postgres:5432/mlflow
      --default-artifact-root ./artifacts
      --host 0.0.0.0
      --port 5000

  # FastAPI Application
  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_password_change_me}@postgres:5432/${POSTGRES_DB:-bankruptcy_db}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - API_SECRET_KEY=${API_SECRET_KEY:-change_this_secret_key_in_production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - postgres
      - mlflow
    volumes:
      - ../../data:/app/data:ro
      - ../../models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  pgadmin_data:
  mlflow_artifacts:
